version: '3.8'

services:
  q2a-web:
    # To build from a Dockerfile uncomment the following lines and adjust accordingly.
    # build:
    #   context: ./
    #   dockerfile: q2a.dockerfile
    image: riovescu/q2a-web:latest
    ports:
      - "9891:80"
    environment:
      QA_DB_USER: "${QA_DB_USER}"
      QA_DB_PASS: "${QA_DB_PASS}"
      QA_DB_NAME: "${QA_DB_NAME}"
    restart: always
    networks:
      - q2a-net

  mysqldb:
    image: mysql:5
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: "${QA_DB_NAME}"
      MYSQL_USER: "${QA_DB_USER}"
      MYSQL_PASSWORD: "${QA_DB_PASS}"
    volumes:
      - mysqldb_data:/var/lib/mysql
    networks:
      - q2a-net

networks:
  q2a-net:
    # In Docker Compose for local development, the default driver is fine. 
    # The overlay driver is specific to Swarm and is not needed here.
    # Removed the `driver: overlay` line.

volumes:
  mysqldb_data:
    # If you need specific options for the volume, you can specify them here.
    # Otherwise, this declaration ensures the volume is managed by Docker.
